// Code generated by xgen. DO NOT EDIT.

package schema

// KpmrSourceTree is Root element containing the hierarchical KPMR source tree structure.
//         The tree represents the parent-child relationships between KPMR assessment factors
//         based on their code identifiers.
type KpmrSourceTree struct {
	KpmrSourceNode []*KpmrSourceNodeType `xml:"KpmrSourceNode"`
}

// KpmrSourceNodeType is Child nodes that are hierarchically related to this node.
//             The parent-child relationship is determined by the code structure:
//             - Parent code ending with 000 (e.g., SK01001000)
//             - Child codes sharing the same prefix with different endings (e.g., SK01001001, SK01001002)
type KpmrSourceNodeType struct {
	Code            string                `xml:"code"`
	RiskId          string                `xml:"risk_id"`
	AssesmentFactor string                `xml:"assesment_factor"`
	Pic             string                `xml:"pic"`
	KpmrSourceNode  []*KpmrSourceNodeType `xml:"KpmrSourceNode"`
}
